### ISSUE TITLE
[Feature] Separare script da dati

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/GraduatorieScriptCSharp#128]

**Comment by lorenzocorallo** [comment]
In teoria anche la 2 fatta.
Direi di monitorare per qualche giorno l'andamento in parallelo delle due repo.

PS. il branch stable che è quello su qui punterà il frontend dovrebbe avere problemi perché cerca di scaricare l'ultima release dello script (ma ancora non ce ne sono, la creo a breve)

**Comment by lorenzocorallo** [comment]
PS.2
Manca anche il trigger che quando viene fatto un cambiamento dello script nel branch main vada a fare reparsing sul branch main dei Dati, mentre quando viene rilasciata una release vada a fare reparsing su stable (e main)

Questo lo devo implementare prima di passare alla fase 3

**Comment by lorenzocorallo** [comment]
Si, bisogna capire se quando si pubblica nuovo codice qua su main triggera il reparse nei Dati

**Comment by lorenzocorallo** [comment]
ora se mergi la PR in teoria dovrebbe triggerare
