### ISSUE TITLE
Perchè c'è stato questo commit?

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/GraduatorieScriptCSharp#130]
https://github.com/PoliNetworkOrg/GraduatorieScriptCSharp/commit/6acce89d715b758c0b4560cab7b0b14583983d98

**Comment by lorenzocorallo** [comment]
🤷🏻‍♂️🤷🏻‍♂️🤷🏻‍♂️

**Comment by lorenzocorallo** [comment]
In realtà perché essendo reparse (scatenato da un update a file .cs) forza la riscrittura di tutto (quindi lastUpdate viene aggiornato)

**Comment by lorenzocorallo** [comment]
è andato a fanculo l'ordinamento quando si scrivono gli indici 

recente 6e94c7c
https://github.com/PoliNetworkOrg/GraduatorieScriptCSharp/blob/6e94c7c5e23d9975ab2af1dfc985f86338a6ab01/data/output/bySchoolYear.json#L1-L7

25/07 d3cf143
https://github.com/PoliNetworkOrg/GraduatorieScriptCSharp/blob/d3cf1433f5221572754661f3854ce1d10e3fb416/data/output/bySchoolYear.json#L1-L7

**Comment by lorenzocorallo** [comment]
sembra essere stato questo commit/PR a fare il casino
1b571424aae51e4c0043dbb92a873b8aaabf1869
