### ISSUE TITLE
Effettuare degli ordinamenti per evitare di generare tutti questi commit

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/GraduatorieScriptCSharp#156]
![immagine](https://github.com/PoliNetworkOrg/GraduatorieScriptCSharp/assets/132761637/073d97c7-bfa5-478a-a5ed-d1173b1e024d)

https://github.com/PoliNetworkOrg/RankingsDati/commits/main/

**Comment by lorenzocorallo** [comment]
adesso sembra pushare un commit al giorno. se expected behaviour chiudiamo

**Comment by lorenzocorallo** [comment]
superseded by #162 and #163
